## All CSV FILES

In [66]:
import pandas as pd
import glob
import numpy as np

In [67]:
import pandas as pd
import glob
import numpy as np

# Get a list of all CSV files in the current directory
csv_files = glob.glob("*.csv")

# Loop through each file and analyze it
for file in csv_files:
    print(f"Analyzing file: {file}")
    df = pd.read_csv(file)
    # print(df.describe())
    # print("Null values in the dataset")
    # print(df.isna().sum())
    # print("Duplicate values in the dataset")
    # print(df.duplicated().sum())
    # print("\n")
    print(df.shape)

Analyzing file: exchange-whale-ratiocryptoquant.csv
(28290, 3)
Analyzing file: inflow_cryptoquant.csv
(28289, 6)
Analyzing file: outflowcryptoquant.csv
(28290, 6)
Analyzing file: premiumindex_cryptoquant.csv
(28283, 6)
Analyzing file: pricecryptoquant.csv
(28291, 7)
Analyzing file: takerbuysellratio_cryptoquant.csv
(28283, 7)

## COMBINING CSV FILES

In [68]:
# Left Join outflowcryptoquant.csv from all other csv files
df1 = pd.read_csv("pricecryptoquant.csv")
for file in csv_files:
    print(f"Joining file: {file}")
    df2 = pd.read_csv(file)
    if 'date_time' in df2.columns:
        df2 = df2.drop(columns=['date_time'])
    # Avoid duplicate column names by renaming or dropping conflicting columns
    common_columns = set(df1.columns).intersection(set(df2.columns)) - {'start_time'}
    df2 = df2.drop(columns=common_columns)
    df1 = pd.merge(df1, df2, on='start_time', how='left', suffixes=('', f'_{file.split(".")[0]}'))

df1.to_csv("joined_data.csv", index=False)
print("Joining completed")

Joining file: exchange-whale-ratiocryptoquant.csv
Joining file: inflow_cryptoquant.csv
Joining file: outflowcryptoquant.csv
Joining file: premiumindex_cryptoquant.csv
Joining file: pricecryptoquant.csv
Joining file: takerbuysellratio_cryptoquant.csv
Joining completed

## ANALYSE COMBINED DATA

### Data Cleaning, removing null

In [69]:
import pandas as pd
df = pd.read_csv("joined_data.csv")
# print(df.head())
# print(df.describe())
# print(df.info())
# print(df.columns)
# print(df.shape)
# print(df.isnull().sum())
# print(df.dtypes)

In [70]:
# Print rows with columns having missing values for datetime column
print(df[df.isnull().any(axis=1)]['datetime'])

7950     2022-11-28 06:00:00
7951     2022-11-28 07:00:00
7952     2022-11-28 08:00:00
7953     2022-11-28 09:00:00
7954     2022-11-28 10:00:00
10265    2023-03-04 17:00:00
10266    2023-03-04 18:00:00
10267    2023-03-04 19:00:00
10268    2023-03-04 20:00:00
10741    2023-03-24 13:00:00
18220    2024-01-30 04:00:00
18221    2024-01-30 05:00:00
23839    2024-09-20 07:00:00
23840    2024-09-20 08:00:00
28289    2025-03-24 17:00:00
28290    2025-03-24 18:00:00
Name: datetime, dtype: object

In [71]:
# Fill missing values with interpolation
# Display how many rows were affected
def fill_missing_values(df):
    df.replace(0, np.nan, inplace=True)
    df.interpolate(method='linear', inplace=True)
    return df

fill_missing_values(df)

C:\Users\ch\AppData\Local\Temp\ipykernel_14560\4087982734.py:5: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate(method='linear', inplace=True)

,start_time,close,datetime,high,low,open,volume,exchange_whale_ratio,inflow_mean,inflow_mean_ma7,...,outflow_total,coinbase_premium_gap,coinbase_premium_gap_usdt_adjusted,coinbase_premium_index,coinbase_premium_index_usdt_adjusted,taker_buy_ratio,taker_buy_sell_ratio,taker_buy_volume,taker_sell_ratio,taker_sell_volume
0,1640995200000,46659.436697,2022-01-01 00:00:00,46730.150302,46189.361554,46193.750668,3941.580414,0.914510,0.364689,0.315172,...,191.145268,0.72,-2.672367,0.001543,-0.005728,0.536151,1.155875,2.206358e+08,0.463849,1.908821e+08
1,1640998800000,46786.785730,2022-01-01 01:00:00,46935.529686,46568.800102,46656.933162,2973.381496,0.736239,0.133690,0.324382,...,183.943318,2.71,5.809987,0.005793,0.012419,0.507326,1.029739,1.708954e+08,0.492674,1.659599e+08
2,1641002400000,46809.021606,2022-01-01 02:00:00,46930.150044,46722.959140,46774.594189,1719.912485,0.963539,0.560280,0.284303,...,164.874141,-3.22,-3.682032,-0.006879,-0.007866,0.469882,0.886372,9.713582e+07,0.530118,1.095880e+08
3,1641006000000,46812.820297,2022-01-01 03:00:00,46907.457847,46750.933449,46813.066972,1564.616584,0.762856,0.224614,0.236203,...,91.269746,-9.19,-10.230657,-0.019631,-0.021855,0.467413,0.877628,8.998186e+07,0.532587,1.025284e+08
4,1641009600000,46704.760647,2022-01-01 04:00:00,46878.235134,46622.668226,46810.681677,2553.921688,0.498040,0.083979,0.230456,...,150.370517,-9.76,-7.823360,-0.020894,-0.016748,0.461228,0.856073,1.310000e+08,0.538772,1.530244e+08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28286,1742824800000,87985.101472,2025-03-24 14:00:00,88782.846329,87666.495321,87707.307934,5230.574828,0.999417,6.652627,6.703631,...,2624.098255,40.56,38.800762,0.046111,0.044112,0.491324,0.965886,1.226270e+09,0.508676,1.269580e+09
28287,1742828400000,88340.623697,2025-03-24 15:00:00,88452.152201,87723.435284,87975.328398,2469.673399,0.998113,0.646185,6.765720,...,437.987233,7.48,12.781001,0.008466,0.014465,0.531716,1.135456,4.533447e+08,0.468284,3.992621e+08
28288,1742832000000,88058.264699,2025-03-24 16:00:00,88508.126165,87692.194807,88346.029661,2257.757537,0.969914,6.216600,6.227667,...,895.171678,18.20,17.319425,0.020668,0.019668,0.485045,0.941916,5.323894e+08,0.514955,5.652199e+08
28289,1742835600000,88481.165675,2025-03-24 17:00:00,88510.550634,87946.250002,88059.493685,1341.238323,0.997611,6.216600,6.227667,...,560.148609,20.46,18.336915,0.023129,0.020729,0.572349,1.338358,3.724836e+08,0.427651,2.783139e+08
28290,1742839200000,88475.392784,2025-03-24 18:00:00,88596.424472,88139.773373,88479.938324,1920.137076,0.997611,6.216600,6.227667,...,560.148609,20.46,18.336915,0.023129,0.020729,0.572349,1.338358,3.724836e+08,0.427651,2.783139e+08

In [72]:
# Print rows with columns having missing values for datetime column
print(df[df.isnull().any(axis=1)]['datetime'])

Series([], Name: datetime, dtype: object)

## Analyse Cleaned Data

In [73]:
df.drop(columns=['coinbase_premium_index_usdt_adjusted','high','low','volume','open','outflow_mean','outflow_mean_ma7','outflow_top10','inflow_mean','inflow_mean_ma7','inflow_top10','high','low','open','volume','taker_buy_ratio','taker_sell_ratio','taker_buy_volume','taker_sell_volume'], inplace=True)

In [74]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28291 entries, 0 to 28290
Data columns (total 10 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   start_time                          28291 non-null  int64
 1   close                               28291 non-null  float64
 2   datetime                            28291 non-null  object
 3   exchange_whale_ratio                28291 non-null  float64
 4   inflow_total                        28291 non-null  float64
 5   outflow_total                       28291 non-null  float64
 6   coinbase_premium_gap                28291 non-null  float64
 7   coinbase_premium_gap_usdt_adjusted  28291 non-null  float64
 8   coinbase_premium_index              28291 non-null  float64
 9   taker_buy_sell_ratio                28291 non-null  float64
dtypes: float64(8), int64(1), object(1)
memory usage: 2.2+ MB

In [ ]:
df['netflow'] = df['inflow_total'] - df['outflow_total']
df.drop(columns=['inflow_total', 'outflow_total'], inplace=True)
df.to_csv("data copy.csv", index=False)